// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Electolab2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	// Cambiar la ruta de chromedriver
	System.setProperty( "webdriver.chrome.driver", "/home/javi-debian/Descargas/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void electolab2() {
    driver.get("http://localhost:8080/G07-2020/");
    driver.manage().window().setSize(new Dimension(1882, 952));
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("root");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("a3");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("a3");
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("a3 a3");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    driver.findElement(By.linkText("Registro")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("a2");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("a2");
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("a2 a2");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("a2");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("a2");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    driver.findElement(By.cssSelector("form:nth-child(1) > .btn-info")).click();
    driver.findElement(By.cssSelector(".asignar-voto-partido:nth-child(1) .radio:nth-child(1)")).click();
    driver.findElement(By.id("PSOE4")).click();
    driver.findElement(By.id("PSOE4")).sendKeys("60");
    driver.findElement(By.id("PSOE4Send")).click();
    driver.findElement(By.id("simular-btn-simulation")).click();
    driver.findElement(By.cssSelector(".btn-info:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".btn-info:nth-child(1)")).click();
    driver.findElement(By.name("simName")).click();
    driver.findElement(By.name("simName")).sendKeys("Prueba 1");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
   // driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".nav-item > .btn")).click();
    driver.findElement(By.cssSelector("form:nth-child(2) > .btn")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("tagProvincia")).click();
    driver.findElement(By.id("Valencia4")).click();
    driver.findElement(By.id("Valencia4")).sendKeys("10");
    driver.findElement(By.cssSelector(".asignar-voto-provincia:nth-child(2) .radio:nth-child(1)")).click();
    driver.findElement(By.id("Valencia4Send")).click();
    driver.findElement(By.cssSelector(".asignar-voto-provincia:nth-child(3) .radio:nth-child(2)")).click();
    driver.findElement(By.id("simular-btn-simulation")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    driver.findElement(By.name("simName")).click();
    driver.findElement(By.name("simName")).sendKeys("Prueba 2");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) .btn")).click();
    driver.findElement(By.linkText("4")).click();
    driver.findElement(By.cssSelector(".sorting:nth-child(4)")).click();
    js.executeScript("window.scrollTo(0,176)");
    driver.findElement(By.cssSelector(".nav-item:nth-child(3) .btn")).click();
    driver.findElement(By.linkText("4")).click();
    driver.findElement(By.linkText("Next")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) .btn")).click();
    driver.findElement(By.cssSelector(".btn-outline-danger")).click();
  }
}
